# Generated by Django 2.2.1 on 2019-10-20 06:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_popularpost_sidebanner1_spheadbanner1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementBlogFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=255, verbose_name='広告タイトル')),
                ('content', ckeditor.fields.RichTextField(default='', verbose_name='内容')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.ParentCategory', verbose_name='表示カテゴリー')),
            ],
            options={
                'verbose_name': 'ブログフッター広告',
                'verbose_name_plural': 'ブログフッター広告',
            },
        ),
    ]
