# Generated by Django 2.2.1 on 2019-10-22 10:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_popularpost_sidebanner1_spheadbanner1'),
        ('advertisement', '0002_auto_20191022_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementBlogSide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=255, verbose_name='広告タイトル')),
                ('content', ckeditor.fields.RichTextField(default='', verbose_name='内容')),
                ('category', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='blog.SubCategory', verbose_name='表示カテゴリー')),
            ],
            options={
                'verbose_name': 'ブログサイド広告',
                'verbose_name_plural': 'ブログサイド広告',
            },
        ),
    ]
