# Generated by Django 2.2.1 on 2019-06-12 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filebrowser.fields
import froala_editor.fields
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(default='', unique=True, verbose_name='スラッグ')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(default='', unique=True, verbose_name='スラッグ')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ParentCategory')),
            ],
            options={
                'verbose_name': 'サブカテゴリ',
                'verbose_name_plural': 'サブカテゴリ',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='メイン画像')),
                ('title', models.CharField(max_length=33, verbose_name='タイトル')),
                ('description', models.TextField(default='', max_length=108, verbose_name='記事概要')),
                ('content', froala_editor.fields.FroalaField(default='', verbose_name='内容')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日')),
                ('is_public', models.BooleanField(default=True, help_text='非公開にする場合はチェックを入れる', verbose_name='公開設定')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('category', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='blog.SubCategory', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '投稿',
                'verbose_name_plural': '投稿',
                'ordering': ['-created_date'],
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
