# Generated by Django 2.2.1 on 2019-07-02 07:01

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filebrowser.fields
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(blank=True, default='<script></script>', null=True, verbose_name='タグ')),
            ],
            options={
                'verbose_name': 'GAタグ',
                'verbose_name_plural': 'GAタグ',
            },
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(default='', unique=True, verbose_name='スラッグ')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(default='', verbose_name='内容')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日')),
                ('is_public', models.BooleanField(default=True, help_text='非公開にする場合はチェックを入れる', verbose_name='公開設定')),
            ],
            options={
                'verbose_name': 'Privacy&Policy',
                'verbose_name_plural': 'Privacy&Policy',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前（表示名）')),
                ('author_image', filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='メイン画像')),
                ('content', ckeditor.fields.RichTextField(default='', verbose_name='内容')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日')),
                ('is_public', models.BooleanField(default=True, help_text='非公開にする場合はチェックを入れる', verbose_name='公開設定')),
            ],
            options={
                'verbose_name': 'プロフィール',
                'verbose_name_plural': 'プロフィール',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(default='', unique=True, verbose_name='スラッグ')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ParentCategory')),
            ],
            options={
                'verbose_name': 'サブカテゴリ',
                'verbose_name_plural': 'サブカテゴリ',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='メイン画像')),
                ('title', models.CharField(max_length=33, verbose_name='タイトル')),
                ('description', models.TextField(default='', max_length=108, verbose_name='記事概要')),
                ('content', ckeditor.fields.RichTextField(default='', verbose_name='内容')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日')),
                ('is_public', models.BooleanField(default=False, help_text='公開にする場合はチェックを入れます。', verbose_name='公開設定')),
                ('is_author', models.BooleanField(default=True, help_text='管理者のみ閲覧可能にする場合は、チェックを入れます。公開前のプレビューとして使用します。', verbose_name='管理者限定表示')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('category', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='blog.SubCategory', verbose_name='カテゴリ')),
                ('relation_posts', models.ManyToManyField(blank=True, related_name='_blogpost_relation_posts_+', to='blog.BlogPost', verbose_name='関連記事')),
            ],
            options={
                'verbose_name': '投稿',
                'verbose_name_plural': '投稿',
                'ordering': ['-created_date'],
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
