# Generated by Django 2.2.1 on 2019-08-23 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideBanner1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'サイドバナー1',
                'verbose_name_plural': 'サイドバナー1',
            },
        ),
        migrations.CreateModel(
            name='SpHeadBanner1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'スマホヘッダーバナー1',
                'verbose_name_plural': 'スマホヘッダーバナー1',
            },
        ),
        migrations.CreateModel(
            name='PopularPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_cnt', models.IntegerField(verbose_name='ページビュー数')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.BlogPost', verbose_name='ブログ')),
            ],
        ),
    ]
