# Generated by Django 2.2.1 on 2019-06-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='relation_posts',
            field=models.ManyToManyField(blank=True, related_name='_blogpost_relation_posts_+', to='blog.BlogPost', verbose_name='関連記事'),
        ),
    ]
