# Generated by Django 2.2.1 on 2019-06-06 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='blog.Category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_public',
            field=models.BooleanField(default=True, help_text='非公開にする場合はチェックを入れる', verbose_name='公開設定'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='カテゴリ名'),
        ),
    ]
