# Generated by Django 2.2.1 on 2019-06-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190606_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='カテゴリ名')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='カテゴリ名')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ParentCategory')),
            ],
            options={
                'verbose_name': 'サブカテゴリ',
                'verbose_name_plural': 'サブカテゴリ',
            },
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='blog.SubCategory', verbose_name='カテゴリ'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
