# Generated by Django 2.2.1 on 2019-06-02 11:13

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190602_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='main_image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='メイン画像'),
        ),
    ]
