# Generated by Django 2.2.1 on 2019-06-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190606_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcategory',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='スラッグ'),
        ),
    ]
