# Generated by Django 2.2.1 on 2019-06-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190602_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_date'], 'verbose_name': '投稿', 'verbose_name_plural': '投稿'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_upload',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='uploads/', verbose_name='Image (Upload)'),
        ),
    ]
