# Generated by Django 2.2.1 on 2019-06-02 13:00

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190602_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_upload',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='uploads/', verbose_name='Image (Upload)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='main_image',
            field=filebrowser.fields.FileBrowseField(blank=True, help_text='画像をアップする場合は<a href="/admin/filebrowser/upload/?" target="_blank">こちら</a>', max_length=200, null=True, verbose_name='メイン画像'),
        ),
    ]
