# Generated by Django 2.2.1 on 2019-06-02 13:33

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190602_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='main_image',
            field=filebrowser.fields.FileBrowseField(blank=True, help_text='画像をアップする場合は<a href="/admin/filebrowser/upload/?pattern=thumb" target="_blank">こちら</a>', max_length=200, null=True, verbose_name='メイン画像'),
        ),
    ]
