# Generated by Django 2.2.1 on 2019-06-02 13:50

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190602_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image_upload',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='main_image',
            field=filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='メイン画像'),
        ),
    ]
