# Generated by Django 2.2.1 on 2019-06-02 13:59

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190602_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='test',
            field=froala_editor.fields.FroalaField(default=''),
        ),
    ]
