# Generated by Django 2.2.1 on 2019-06-02 14:01

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpost_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='live',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='text',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=froala_editor.fields.FroalaField(default='', verbose_name='内容'),
        ),
    ]
