# Generated by Django 2.2.1 on 2019-06-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_blogpost_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='公開可能か?'),
        ),
    ]
