# Generated by Django 2.2.1 on 2019-06-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190604_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(default='', max_length=110, verbose_name='記事概要'),
        ),
    ]
