# Generated by Django 2.2.1 on 2019-06-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190604_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(default='', max_length=108, verbose_name='記事概要'),
        ),
    ]
