# Generated by Django 2.2.1 on 2019-06-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190604_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='is_public',
            field=models.BooleanField(default=True, help_text='非公開にする場合はチェックをはすず', verbose_name='公開設定'),
        ),
    ]
